let url = "http://localhost:8088" ;
url = "http://10.24.1.8:8088" ;
const myInterface = {
    "origin":url,
    "login":url+"/user/loginDao",
    "regist":url+"/user/registDao",
    "addVideoGroup":url+"/user/addVideoGroup",
    "getVideoGroup":url+"/user/getVideoGroup",
    "uploadVideoGroupCoverUrl":url+"/upload/uploadFile",
    "uploadIcon":url+"/upload/uploadFile",
    "addVideo":url+"/upload/uploadFile",
    "addGroupAttachement":url+"/upload/uploadFile",
    "updPassword":url+"/user/updPassword",
    "updUser":url+"/user/updUser",
    "requestGroup":url+"/user/requestGroup",
    "selectVideoGroupInfoByCategory":url+"/user/selectVideoGroupInfoByCategory",
    "videoUrl":url+"/video/play",
    "deleteGroup":url+"/user/deleteGroup",
    "userIcon":url+"/image/getImg",
    "coverApi":"/image/getImg",
    "concern":url+"/user/concern",
    "like":url+"/user/like",
    "collect":url+"/user/collect",
    "interaction":url+"/user/getInteraction",
    "sendComment":url+"/user/sendComment",
    "getAuthor":url+"/user/getAuthor",
    "getStatistics":url+"/user/getStatistics",
    "adminLogin":url+"/admin/loginDo",
    "adminRegist":url+"/admin/registDo",
    "getUserList":url+"/admin/getUserList",
    "editUserState":url+"/admin/editUserState",
    "deleteUser":url+"/admin/deleteUser",
    "getGroupList":url+"/admin/getGroupList",
    "editGroupState":url+"/admin/editGroupState",
    "adminDeleteGroup":url+"/admin/adminDeleteGroup",
    "addVideoInfo":url+"/upload/addVideo",
    "addPlayCount":url+"/user/addPlayCount",
    "getAdminMenu":url+"/admin/getAdminMenu",
    "getAdminList":url+"/admin/getAdminList",
    "updAdmin":url+"/admin/updAdmin",
    "deleteAdmin":url+"/admin/deleteAdmin",
    "requestPermissionList":url+"/admin/getPermissionList",
    "savePermission":url+"/admin/savePermission",
    "updPermission":url+"/admin/updPermission",
    "deletePermission":url+"/admin/deletePermission",
    "downLoad":url+"/download/file",
    "saveTask":url+"/admin/saveTask",
    "adminGetTasks":url+"/admin/getTasks",
    "touristGetTasks":url+"/tourist/getTasks",
    "touristGetWorks":url+"/tourist/getWorks",
    "deleteTask":url+"/admin/deleteTask",
    "uploadTaskProject":url+"/upload/uploadFile",
    "adminGetWorks":url+"/admin/getWorks",
    "updateWork":url+"/admin/updateWork",
    "adminDeleteWork":url+"/admin/deleteWork",
    "setVotes":url+"/tourist/setVotes",
    "getAnotherVideos":url+"/video/anotherVideos",
    "crawlerVideos":url+"/video/crawlerVideos"
};

myInterface.install = function(Vue){
    Vue.prototype.$myInterface = myInterface;
}
export default myInterface ;